// <auto-generated />
using System;
using Appdoptanos.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace appdoptanosV2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Appdoptanos.Api.Models.Adopcion", b =>
                {
                    b.Property<int>("IdAdopcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AdoptanteUserId")
                        .HasColumnType("int");

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("RescatistaUserId")
                        .HasColumnType("int");

                    b.HasKey("IdAdopcion");

                    b.HasIndex("AdoptanteUserId");

                    b.HasIndex("AnimalId")
                        .IsUnique();

                    b.HasIndex("RescatistaUserId");

                    b.ToTable("Adopcion");
                });

            modelBuilder.Entity("Appdoptanos.Api.Models.Animal", b =>
                {
                    b.Property<int>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<bool>("Disponibilidad")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FecNac")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("IdAnimal");

                    b.ToTable("Animal");
                });

            modelBuilder.Entity("Appdoptanos.Api.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Dni")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Localidad")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("NombreUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PerfilVerificado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Provincia")
                        .HasColumnType("longtext");

                    b.Property<int?>("Reputacion")
                        .HasColumnType("int");

                    b.HasKey("IdUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Appdoptanos.Api.Models.Adopcion", b =>
                {
                    b.HasOne("Appdoptanos.Api.Models.User", "AdoptanteUser")
                        .WithMany("Adoptados")
                        .HasForeignKey("AdoptanteUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Appdoptanos.Api.Models.Animal", "Animal")
                        .WithOne("Adopcion")
                        .HasForeignKey("Appdoptanos.Api.Models.Adopcion", "AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Appdoptanos.Api.Models.User", "RescatistaUser")
                        .WithMany("Rescatados")
                        .HasForeignKey("RescatistaUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdoptanteUser");

                    b.Navigation("Animal");

                    b.Navigation("RescatistaUser");
                });

            modelBuilder.Entity("Appdoptanos.Api.Models.Animal", b =>
                {
                    b.Navigation("Adopcion");
                });

            modelBuilder.Entity("Appdoptanos.Api.Models.User", b =>
                {
                    b.Navigation("Adoptados");

                    b.Navigation("Rescatados");
                });
#pragma warning restore 612, 618
        }
    }
}
